## 脚本启动参数
load_functional_script:
  btn1:
    name: "MID360建图(MID360定位下无需启动)"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/mid360_output.sh"
    close_cmd: "rosnode kill /fliter_points /laserMapping /livox_lidar_publisher2 /tf_MID360"
    mode: 2
    node_name: "/fliter_points | /laserMapping | /livox_lidar_publisher2 | /tf_MID360"  # 当mode为2时，在启动的时候会去检测是否存在该节点，不存在则启动，存在则会提示用户先关闭在启动
    detection_cmd: ""  # 当mode为3时，在启动的时候会去运行该检测命令，存在则返回true，不存在返回false，且会提示用户先关闭在启动
    flag: 1 # 启动位置
  btn2:
    name: "D435i小车点击跟踪"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/car_detection_with_tracking_d435i.sh"
    close_cmd: "rosnode kill /car_detection_with_d435i /yolov5_tracking"
    mode: 2
    node_name: "/car_detection_with_d435i | /yolov5_tracking"  # 当mode为2时，在启动的时候会去检测是否存在该节点，不存在则启动，存在则会提示用户先关闭在启动
    detection_cmd: ""  # 当mode为3时，在启动的时候会去运行该检测命令，存在则返回true，不存在返回false，且会提示用户先关闭在启动
    flag: 1 # 启动位置
  btn3:
    name: "D435i二维码点击跟踪"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/aruco_detection_with_d435i.sh"
    close_cmd: "rosnode kill /aruco_detection_with_d435i /aruco_tracking"
    mode: 2
    node_name: "/aruco_detection_with_d435i | /aruco_tracking"  # 当mode为2时，在启动的时候会去检测是否存在该节点，不存在则启动，存在则会提示用户先关闭在启动
    detection_cmd: ""  # 当mode为3时，在启动的时候会去运行该检测命令，存在则返回true，不存在返回false，且会提示用户先关闭在启动
    flag: 1 # 启动位置
  btn4:
    name: "室内D435i-EGO避障"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/d435i_ego_indoor.sh"
    close_cmd: "rosnode kill /aruco_detection_with_d435i /aruco_tracking"
    mode: 2
    node_name: "/aruco_detection_with_d435i | /aruco_tracking"  # 当mode为2时，在启动的时候会去检测是否存在该节点，不存在则启动，存在则会提示用户先关闭在启动
    detection_cmd: ""  # 当mode为3时，在启动的时候会去运行该检测命令，存在则返回true，不存在返回false，且会提示用户先关闭在启动
    flag: 1 # 启动位置
  btn5:
    name: "室内D435i-EGO避障"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/d435i_ego_indoor.sh"
  btn6:
    name: "室外D435i-EGO避障"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/d435i_ego_outdoor.sh"
  btn7:
    name: "室内S3Lidar-EGO避障"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/lidar_ego_indoor_s3.sh"
  btn8:
    name: "室外S3Lidar-EGO避障"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/lidar_ego_outdoor_s3.sh"
  btn9:
    name: "室内G1小车点击跟踪"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/gimbal_tracking_t265.sh"
  btn10:
    name: "室外G1目标点击跟踪"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/gimbal_tracking.sh"
  btn11:
    name: "G1二维码点击降落"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/gimbal_aruco_with_landing.sh"
  btn12:
    name: "MID360-EGO避障"
    cmd: "/home/amov/p450_experiment/src/p450_experiment/scripts/mid360_ego.sh"
  btn13:
    name: "Trajectory轨迹控制"
    cmd: "roslaunch prometheus_uav_control uav_command_pub.launch"
  btn14:
    name: "ekf2 stop"
    cmd: "mavlink_console:ekf2 stop"
  btn15:
    name: "ekf2 start"
    cmd: "mavlink_console:ekf2 start"

